### ISSUE TITLE
Bug: Broadcast is completed but not all messages are sent

### ISSUE THREAD

**Issue by lukoerfer** [Notifuse/notifuse#157]
We tried our first large broadcast today and sadly it seems like not all messages are sent by Notifuse, even if the status shows the broadcast is completed:
<img width="498" height="398" alt="Image" src="https://github.com/user-attachments/assets/68f9f73b-9f15-4b51-9cac-ece2cf937484" />

Is there a reason for this behavior of Notifuse?

We can also check in Mailgun that only 6280 mails were sent, so what is the reason Notifuse stopped sending the mails?

**Comment by lukoerfer** [comment]
We took a look at the logs and it seems like we found the entry where Notifuse decides that the broadcast is completed:
```
{"level":"info","broadcast_id":"4780e5f6e514bb71354a684a4eaccf43","workspace_id":"cimaachen","total":50,"sent":50,"failed":0,"time":"2025-12-11T12:48:16Z","message":"Batch send completed"}
{"level":"info","broadcast_id":"4780e5f6e514bb71354a684a4eaccf43","phase":"single","sent_count":6275,"processed_count":6275,"progress":91.95486518171161,"elapsed":"14.254485481s","task_id":"7aabacaa-7de2-46c3-9534-efbb7482b88b","failed_count":0,"phase_offset":6275,"phase_limit":6824,"total_count":6824,"time":"2025-12-11T12:48:16Z","message":"Broadcast progress update"}
{"level":"info","workspace_id":"cimaachen","offset":6275,"limit":50,"contacts_fetched":5,"with_list_info":true,"broadcast_id":"4780e5f6e514bb71354a684a4eaccf43","time":"2025-12-11T12:48:16Z","message":"Fetched recipient batch with list info"}
{"level":"info","broadcast_id":"4780e5f6e514bb71354a684a4eaccf43","workspace_id":"cimaachen","integration_rate_limit":500,"recipients":5,"time":"2025-12-11T12:48:16Z","message":"Starting batch send with rate limiting"}
{"level":"info","workspace_id":"cimaachen","count":1,"time":"2025-12-11T12:48:16Z","message":"Processing contact segment queue"}
{"level":"info","provider":"mailgun","workspace_id":"cimaachen","integration_id":"83f9b214-9a3b-4a3a-957e-231e14fb4042","time":"2025-12-11T12:48:16Z","message":"Received webhook event"}
{"level":"info","provider":"mailgun","workspace_id":"cimaachen","integration_id":"83f9b214-9a3b-4a3a-957e-231e14fb4042","time":"2025-12-11T12:48:16Z","message":"Received webhook event"}
{"level":"info","provider":"mailgun","workspace_id":"cimaachen","integration_id":"83f9b214-9a3b-4a3a-957e-231e14fb4042","time":"2025-12-11T12:48:17Z","message":"Received webhook event"}
{"level":"info","provider":"mailgun","workspace_id":"cimaachen","integration_id":"83f9b214-9a3b-4a3a-957e-231e14fb4042","time":"2025-12-11T12:48:17Z","message":"Received webhook event"}
2025/12/11 12:48:17 path notification_center/dist/
2025/12/11 12:48:17 path notification_center/dist/assets/index-CUQiWu9e.js
2025/12/11 12:48:17 path notification_center/dist/assets/index-BQuRU5r5.css
{"level":"info","provider":"mailgun","workspace_id":"cimaachen","integration_id":"83f9b214-9a3b-4a3a-957e-231e14fb4042","time":"2025-12-11T12:48:17Z","message":"Received webhook event"}
2025/12/11 12:48:17 path notification_center/dist/assets/index-CUQiWu9e.js
{"level":"info","provider":"mailgun","workspace_id":"cimaachen","integration_id":"83f9b214-9a3b-4a3a-957e-231e14fb4042","time":"2025-12-11T12:48:17Z","message":"Received webhook event"}
{"level":"info","broadcast_id":"4780e5f6e514bb71354a684a4eaccf43","workspace_id":"cimaachen","total":5,"sent":5,"failed":0,"time":"2025-12-11T12:48:17Z","message":"Batch send completed"}
{"level":"info","broadcast_id":"4780e5f6e514bb71354a684a4eaccf43","workspace_id":"cimaachen","offset":6280,"limit":50,"contacts_fetched":0,"with_list_info":true,"time":"2025-12-11T12:48:17Z","message":"Fetched recipient batch with list info"}
{"level":"info","broadcast_id":"4780e5f6e514bb71354a684a4eaccf43","offset":6280,"phase":"single","task_id":"7aabacaa-7de2-46c3-9534-efbb7482b88b","time":"2025-12-11T12:48:17Z","message":"No more recipients to process"}
{"level":"info","task_id":"7aabacaa-7de2-46c3-9534-efbb7482b88b","broadcast_id":"4780e5f6e514bb71354a684a4eaccf43","sent_count":6280,"failed_count":0,"phase":"single","time":"2025-12-11T12:48:17Z","message":"Broadcast marked as sent successfully"}
{"level":"info","progress":92.02813599062134,"all_done":true,"task_id":"7aabacaa-7de2-46c3-9534-efbb7482b88b","broadcast_id":"4780e5f6e514bb71354a684a4eaccf43","sent_total":6280,"failed_total":0,"total_recipients":6824,"time":"2025-12-11T12:48:17Z","message":"Broadcast processing cycle completed"}
```

In the last line it says `"all_done":true` despite having `"progress":92.02813599062134`, `"sent_total":6280` and `"total_recipients":6824`.

**Comment by pierre-b** [comment]
Hi @lukoerfer could you please share the exact mailing list active subscribers count at the moment of the sending? (without unsubscribed...)

**Comment by pierre-b** [comment]
Was this broadcast targeting a single list, or did it use segments?

**Comment by lukoerfer** [comment]
There were no unsubscribed contacts at the moment of the sending, because we did a fresh import of the full list and it was actually our first newsletter using Notifuse (currently trying to migrate from Zoho Campaigns). We did not use segments for this broadcast and just a single list.

**Comment by pierre-b** [comment]
Thanks for the detailed logs - they were very helpful in tracking this down.

Root cause: when contacts are bulk imported (like your migration from Zoho Campaigns), they all get the same  created_at timestamp. The broadcast pagination was using ORDER BY  created_at ASC without a secondary sort key, making the order  non-deterministic across batches.

With PostgreSQL's OFFSET/LIMIT pagination and unstable ordering, some contacts were being skipped between batches - explaining the  544 missing recipients (6,824 total vs 6,280 sent).

Fixed in https://github.com/Notifuse/notifuse/releases/tag/v19.4 , docker image are building, should be live in 30 mins!

**Comment by pierre-b** [comment]
Let me know if bug persist, I'll reopen the issue;

**Comment by lukoerfer** [comment]
Thank you very much for your quick fix to this problem. Using Mailgun logs, we were able to get a list of mail adresses where a mail was sent to, we can use this to create a list of contacts that did not get a mail yet. We will use this list for another broadcast on Monday after updating Notifuse.

During our first "production run" using Notifuse we also encountered some other bugs or annoyances, so I may create one or two more issues in the next few days.

**Comment by pierre-b** [comment]
Thanks @lukoerfer for helping improving Notifuse! feel free to report any issue

**Comment by lukoerfer** [comment]
We updated Notifuse to v19.4, but it seems like the issue still persists. Please note, that we did not reimport the contacts, so the `created_at` timestamp will be the same. We just started a new broadcast with the same template and limited (using a segment) to the contacts that did no receive a newsletter before.

<img width="550" height="383" alt="Image" src="https://github.com/user-attachments/assets/e36975f8-ca1a-46a3-b36d-e33e2e223b2f" />

**Comment by pierre-b** [comment]
is the bottom left corner of the console shows 19.4?

**Comment by pierre-b** [comment]
I suspect a race condition maybe... are you running the deprecated cron `/api/cron` still?

**Comment by pierre-b** [comment]
The pagination bug was fixed in v19.4. However, I've identified a secondary issue that explains why the logs showed progress: 92% while all_done: true.

Root cause: The MarkAsCompleted method doesn't save  the final task state. It only sets progress=100 and status=completed, but leaves the state JSON unchanged from the last periodic save.

What happens:
  1. During broadcast, SaveProgressState saves state  periodically (e.g., at 92%)
  2. Final batch completes → all emails sent
  3. MarkAsCompleted is called → sets progress=100 but  doesn't update state
  4. Result: progress=100 but state.message still shows "92%"

This is a display bug only - all emails are actually delivered. The state just doesn't reflect the final counts.

**Comment by pierre-b** [comment]
The fix is in https://github.com/Notifuse/notifuse/releases/tag/v19.5 , the docker images should be live in 30mins.

**Comment by sky-cim** [comment]
I work with lukoerfer, and unfortunately, the problem here is not a display bug. During our second attempt, only 1,635 emails were sent via Mailgun, rather than the 1,836 emails that were supposed to be sent. I was able to determine this by comparing the Mailgun logs with our recipient list. We have updated to version 19.4. Version 19.4 is also displayed on the web interface. With version 19.4, no emails were sent twice to the same person this time. However, the problem that not everyone on the list received an email still persisted. We have not yet tried version 19.5.

**Comment by pierre-b** [comment]
The v19.5 brings cursor-based pagination (on the email address) for broadcast contacts retrieval, because even with a dual sort it could skip contacts having same timestamp.
